"""cria_tabelas_recomendacao

Revision ID: 8a84c85f4cb8
Revises: 
Create Date: 2026-06-28 13:21:15.782700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a84c85f4cb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicos_leitura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_livro', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicos_leitura_id_usuario'), 'historicos_leitura', ['id_usuario'], unique=False)
    op.create_table('popularidades_livros',
    sa.Column('id_livro', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('total_emprestimos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_livro')
    )
    op.create_index(op.f('ix_popularidades_livros_total_emprestimos'), 'popularidades_livros', ['total_emprestimos'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_popularidades_livros_total_emprestimos'), table_name='popularidades_livros')
    op.drop_table('popularidades_livros')
    op.drop_index(op.f('ix_historicos_leitura_id_usuario'), table_name='historicos_leitura')
    op.drop_table('historicos_leitura')
    # ### end Alembic commands ###
